/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.skourtis.sqladmin.view;

import java.sql.SQLException;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;
import net.skourtis.sqladmin.model.Column;
import net.skourtis.sqladmin.model.Constraint;
import net.skourtis.sqladmin.model.Table;
import net.skourtis.sqladmin.utils.Utils;

/**
 *
 * @author Stavros
 */
public class TablePanel extends javax.swing.JPanel {

    private Table table;

    /**
     * Creates new form TablePanel
     */
    public TablePanel(Table table) {
        this.table = table;
        initComponents();
        tableTitle.setText(table.getName());
        refreshLabel.setVisible(false);
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        asdasdasd = new javax.swing.JScrollPane();
        constraintsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        refreshLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tableTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableTitle.setText("Name");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(detailsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("Columns", jPanel1);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jTabbedPane1.addTab("Data", jPanel2);

        asdasdasd.setPreferredSize(new java.awt.Dimension(1000, 402));

        constraintsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        constraintsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        asdasdasd.setViewportView(constraintsTable);

        jTabbedPane1.addTab("Constraints", asdasdasd);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        refreshLabel.setIcon(new javax.swing.ImageIcon("E:\\Copy\\Code\\Personal\\SQL Admin for oracle\\res\\ui\\loading1.gif")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(refreshLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void refresh() {
        refreshLabel.setVisible(true);
        try {
            table.refresh();
        } catch (SQLException ex) {
        }

        /*
         setup data table
         */
        dataTable.setModel(Utils.dataToTableModel(table.getColumns()));
        dataTable.repaint();

        /*
         setup columns table
         */
        LinkedList<Column> cols = table.getColumns();

        String[] names = {"Name", "Type", "Nullable", "Auto Increment"};
        String[][] d = new String[cols.size()][names.length];

        for (int i = 0; i < cols.size(); i++) {
            d[i][0] = cols.get(i).getName();
        }
        for (int i = 0; i < cols.size(); i++) {
            d[i][1] = cols.get(i).getTypeName();
        }
        for (int i = 0; i < cols.size(); i++) {
            d[i][2] = cols.get(i).isNullable() ? "True" : "False";
        }
        for (int i = 0; i < cols.size(); i++) {
            d[i][3] = cols.get(i).isAutoIncrement() ? "True" : "False";
        }

        detailsTable.setModel(new TableModel(d, names));
        detailsTable.repaint();

        
        Set<String> labelSet = new HashSet<>();
        

        for (int i = 0; i < table.getConstrains().size(); i++) {
            Set<String> keys = table.getConstrains().get(i).getKeys();
            labelSet.addAll(keys);
        }
        
        String labels [] = new String[labelSet.size()];
        
        int k=0;
        for (String label : labelSet) {
            labels[k++] = label;
        }

        LinkedList<Constraint> constraints = table.getConstrains();
        String[][] data = new String[constraints.size()][labels.length];
        
        for (int i = 0; i < data.length; i++) {

            for (int j = 0; j < data[i].length; j++) {
                
                String temp = constraints.get(i).get(labels[j]);
                data[i][j] = temp==null?"null":temp;
            }
        }
        constraintsTable.setModel(new TableModel(data, labels));
        constraintsTable.repaint();
        
        for ( int i=0; i<labels.length ;i++) {
            constraintsTable.getColumnModel().getColumn(i).setPreferredWidth(120);
        }
        
        refreshLabel.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane asdasdasd;
    private javax.swing.JTable constraintsTable;
    private javax.swing.JTable dataTable;
    private javax.swing.JTable detailsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JLabel tableTitle;
    // End of variables declaration//GEN-END:variables
}
